#!/usr/bin/env python3

# GEP2 Super-Report Generator
# 2026
# by @mxmmns based on @diegomics guidelines
# AI tools may have been used

# This script is part of the GEP2 pipeline

# Aggregates results from multiple {asm_id}_report.md files (generated by
# make_gep2_report.py) into a single overview table across a GEP2 pipeline
# run (or just multiple .md-files created from multiple pipeline run's).
# The generated report has a heatmap-style quality rating based on EBP/VGP-standards.

from __future__ import annotations

import argparse
import os
import re
import sys
import pandas as pd
from datetime import datetime, timezone
from typing import Any, Optional

__version__ = "0.1.0"

# -------------------------------------------------------------------------------
# MARKDOWN-REPORT-PARSING
# -------------------------------------------------------------------------------

def _clean_numeric(raw: str) -> Optional[float]:
    """
    Removes table formatting (thousand separators, % signs) and converts
    to float. Returns None for 'N/A' or empty cells.
    """
    raw = raw.strip()
    if (not raw) or raw.upper() in ("N/A", "NAN"):
        return None
    raw = raw.replace(",", "").replace("%", "").strip()
    try:
        return float(raw)
    except ValueError:
        return None
    
def _clean_rating(raw:str) -> str:
    raw = raw.strip()
    if (not raw) or raw.upper() in ("N/A", "NAN"):
        return None
    raw = raw.replace("`", "")
    try: 
        return str(raw)
    except Exception:
        return None
    
def _map_metric_label(label: str) -> Optional[str]:
    """
    Maps a metric label from the Markdown table (e.g., 'COMPL Sing. (e)' to the internal column name (e.g., 'eukaryota_single').
    
    Uses partial string matching instead of an exact dictionary, because the label varies depending on
    the pipeline configuration (COMPL vs. BUSCO, MERQ vs. MERQ.FK, (e) vs. (x) for the second lineage). 
    
    Unknown/unnecessary labels (e.g., 'GC %', 'Scaffolds') are intentionally ignored (None).
    """
    
    label = re.sub(r"\s+", " ", label.strip())
    
    if label == "Total bp":
        return "total_bp"
    if label.startswith("Contig N50"):
        return "contig_n50"
    if label.startswith("Scaffold N50"):
        return "scaffold_n50"
    if label.startswith("Gaps/Gbp"):
        return "gaps_per_gbp"
    if label.startswith("Scaffold L90"):
        return "scaffold_l90"
    if label.startswith(("COMPL Sing.", "BUSCO Sing.")):
        return "eukaryota_single" if "(e)" in label else "other_single"
    if label.startswith(("COMPL Dupl.", "BUSCO Dupl.")):
        return "eukaryota_dupl" if "(e)" in label else "other_dupl"
    if label.startswith("INSP Str. Error"):
        return "structural_errors"
    if label.endswith("QV"):
        return "merqury_qv"
    if label.endswith("Compl.") and not label.startswith(("COMPL", "BUSCO")):
        return "merqury_completeness"
    
    return None

def parse_assembly_report(report_path: str) -> dict[str, Any]:
    """
    Parses a previously generated {asm_id}_report.md file (from make_gep2_report.py) and extracts raw data from it.
    """
    
    with open(report_path, encoding="utf-8") as f:
        content = f.read()
        
    result: dict[str, Any] = {
        "species": None, "taxon_id": None, "family": None, "asm_id": None,
        "haploid_number": None, "num_assemblies": 0, "completeness_tool": None, "kmer_tool": None,
        "metrics": {}
    }
    
    header_match = re.search(r"^### (.+?) \(ID:\s*(.+?)\)\s*$", content, re.MULTILINE)
    if header_match:
        result["species"] = header_match.group(1).strip()
        taxon_id_raw = header_match.group(2).strip()
        result["taxon_id"] = None if taxon_id_raw == "not found" else taxon_id_raw

    family_match = re.search(r"^##### (.+)$", content, re.MULTILINE)    
    if family_match:
        result["family"] = family_match.group(1).strip()
    
    asm_id_match = re.search(r"^#### (.+)$", content, re.MULTILINE)
    if asm_id_match:
        result["asm_id"] = asm_id_match.group(1).strip()
    
    haploid_match = re.search(r"Haploid number is (\d+) \(([^,]+),", content)
    if haploid_match:
        result["haploid_number"] = int(haploid_match.group(1))
        result["haploid_source"] = haploid_match.group(2).strip()
    else:
        fallback_match = re.search(r"Haploid number is (\d+)", content)
        if fallback_match:
            result["haploid_number"] = int(fallback_match.group(1))
    
    euka_lineage_match = re.search(r"^e = (.+?)<br>", content, re.MULTILINE)
    if euka_lineage_match:
        result["eukaryota_lineage"] = euka_lineage_match.group(1).strip()
 
    other_lineage_match = re.search(r"^x = (.+?)<br>", content, re.MULTILINE)
    if other_lineage_match:
        result["other_lineage"] = other_lineage_match.group(1).strip()
    
    table_lines = [l for l in content.splitlines() if l.strip().startswith("|")]
    if table_lines:
        header_cells = [c.strip() for c in table_lines[0].strip().strip("|").split("|")]
        num_assemblies = 2 if "asm2 value" in header_cells else 1
        result["num_assemblies"] = num_assemblies
 
        for line in table_lines[2:]:  # skip header + separator row
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) < 3:
                continue
 
            normalized_label = re.sub(r"\s+", " ", cells[0].strip())
            internal_key = _map_metric_label(cells[0])
 
            if normalized_label.startswith(("COMPL", "BUSCO")):
                result["completeness_tool"] = "BUSCO" if normalized_label.startswith("BUSCO") else "compleasm"
            if normalized_label.startswith(("MERQ",)):
                result["kmer_tool"] = "MerquryFK" if normalized_label.startswith("MERQ.FK") else "Merqury"
 
            if internal_key is None:
                continue
 
            values = [_clean_numeric(cells[1])]
            ratings = [_clean_rating(cells[2])]
            
            if num_assemblies == 2 and len(cells) >= 4:
                
                values.append(_clean_numeric(cells[3]))
                ratings.append(_clean_rating(cells[4]))
                
            result["metrics"][internal_key] = tuple([values, ratings])
 
    return result
    
# -------------------------------------------------------------------------------
# AGGREGATION ACROSS ALL ASSEMBLIES
# -------------------------------------------------------------------------------

def build_super_table(all_reports: list[dict[str, Any]]) -> pd.DataFrame:
    """
    The list of parsed reports is build into one table: one
    row per individual assembly file (e.g., asm1 '\n' asm2 for diploid assemblies).
    
    Different reports may have used different tools.
    
    They are used in render_markdown_table() for the
    markers/legend and are removed from the visible table there.
    """
    
    rows: list[dict[str, Any]] = []
    
    for entry in all_reports:
        species: str = entry["species"]
        asm_id: str = entry["asm_id"]
        num_assemblies = entry["num_assemblies"]
        metrics = entry["metrics"]
        
        base_fields = {
            "species": species,
            "asm_id": asm_id,
            "taxon_id": entry.get("taxon_id"),
            "family": entry.get("family"),
            "haploid_number": entry.get("haploid_number"),
            "haploid_source": entry.get("haploid_source"),
            "completeness_tool": entry.get("completeness_tool"),
            "kmer_tool": entry.get("kmer_tool"),
        }
        
        if num_assemblies == 0:
            rows.append({**base_fields, "asm_file_nr": None})
            continue
        
        for i in range(num_assemblies):
            row: dict[str, Any] = {**base_fields, "asm_file_nr": i + 1}
            for metric_key, (values, ratings) in metrics.items():
                
                row[metric_key] = values[i] if i < len(values) else None
                
                metrik_key_rating = f"{metric_key}_rating"
                row[metrik_key_rating] = ratings[i] if i < len(ratings) else None
                
            euka_single = row.pop("eukaryota_single", None)
            euka_dupl = row.pop("eukaryota_dupl", None)
            other_single = row.pop("other_single", None)
            other_dupl = row.pop("other_dupl", None)
            
            euka_single_rating = row.pop("eukaryota_single_rating", None)
            euka_dupl_rating = row.pop("eukaryota_dupl_rating", None)
            other_single_rating = row.pop("other_single_rating", None)
            other_dupl_rating = row.pop("other_dupl_rating", None)
            
            has_euka = euka_single is not None or euka_dupl is not None
            has_other = other_single is not None or other_dupl is not None
            
            if has_euka and has_other:
                print(
                    f"Warning: {species}/{asm_id} (file #{i + 1}) has both a eukaryota and a species-specific lineage result. "
                    f"keeping only the species-specific one ('{entry.get('other_lineage')}'). eukaryota values are dropped from the merged lineage column.",
                    file=sys.stderr
                )

            if has_other:
                row["lineage"] = entry.get("other_lineage")
                row["gene_compl_single"] = other_single
                row["gene_compl_dupl"] = other_dupl
                row["gene_compl_single_rating"] = other_single_rating
                row["gene_compl_dupl_rating"] = other_dupl_rating
            elif has_euka:
                row["lineage"] = entry.get("eukaryota_lineage")
                row["gene_compl_single"] = euka_single
                row["gene_compl_dupl"] = euka_dupl
                row["gene_compl_single_rating"] = euka_single_rating
                row["gene_compl_dupl_rating"] = euka_dupl_rating
            else:
                row["lineage"] = None
                row["gene_compl_single"] = None
                row["gene_compl_dupl"] = None
                row["gene_compl_single_rating"] = None
                row["gene_compl_dupl_rating"] = None

            rows.append(row)

    return pd.DataFrame(rows)

# -------------------------------------------------------------------------------
# RENDERING / OUTPUT
# -------------------------------------------------------------------------------

COLUMN_DISPLAY_NAMES: dict[str, str] = {
    "species": "Species",
    "asm_id": "Assembly ID",
    "taxon_id": "Taxon ID",
    "family": "Family",
    "haploid_number": "Haploid Number",
    "asm_file_nr": "File #",
    "total_bp": "Total bp",
    "gaps_per_gbp": "Gaps/Gbp",
    "scaffold_n50": "Scaffold N50",
    "scaffold_l90": "Scaffold L90",
    "contig_n50": "Contig N50",
    "lineage": "Lineage",
    "gene_compl_single": "Gene Compl. Single (%)",
    "gene_compl_dupl": "Gene Compl. Dupl. (%)",
    "merqury_qv": "k-mer QV",
    "merqury_completeness": "k-mer Compl. (%)",
    "structural_errors": "Structural Errors",
}

# Columns that identify/describe an assembly rather than measure it, to be kept
PROTECTED_COLUMNS = {"species", "asm_id", "asm_file_nr"}

# Text-valued columns
TEXT_COLUMNS = ["Species", "Assembly ID", "Taxon ID", "Family", "Lineage"]

COLUMN_ORDER = [
    "species", "asm_id", "taxon_id", "family", "haploid_number", "asm_file_nr",
    "total_bp", "gaps_per_gbp", "scaffold_n50",  "scaffold_l90", "contig_n50", 
    "lineage", "gene_compl_single", "gene_compl_dupl",
    "merqury_qv", "merqury_completeness",
    "structural_errors"
]

BP_SCALE_COLUMNS = ["total_bp", "contig_n50", "scaffold_n50"]

def _format_bp(value: Any, human_readable: bool) -> str:
    """
    Formats bp-scaled values for the table.
    - human_readable=True -> shortened unit e.g. "2.46 Mb"
    - None / NaN -> empty string instead of "nan" in the table.
    """
    if value is None or (isinstance(value, float)) and pd.isna(value):
        return ""
    
    value = float(value)
    
    if not human_readable:
        return f"{value:,.0f}"
    
    abs_value = abs(value)
    if abs_value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.2f} Gb"
    if abs_value >= 1_000_000:
        return f"{value / 1_000_000:.2f} Mb"
    if abs_value >= 1_000:
        return f"{value / 1_000:.2f} Kb"
    
    return f"{value:.0f} bp"    

PLAIN_NUMERIC_COLUMNS: dict[str, int] = {
    "gaps_per_gbp": 1,
    "scaffold_l90": 0,
    "structural_errors": 0,
    "gene_compl_single": 2,
    "gene_compl_dupl": 2
}

def _format_plain_numeric(value: Any, decimals: int) -> str:
    """Formats a non-bp numeric value without scientific notation, at a
    fixed number of decimals. Empty string instead of "nan" for missing values."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    return f"{float(value):,.{decimals}f}"

# Tool-neutral column labels + markers instead of tool-specific names
COMPLETENESS_COLUMNS = ["eukaryota_single", "eukaryota_dupl", "other_single", "other_dupl"]
KMER_COLUMNS = ["merqury_qv", "merqury_completeness"]
 
COMPLETENESS_TOOL_MARKERS: dict[str, str] = {"BUSCO": "*", "compleasm": "**"}
KMER_TOOL_MARKERS: dict[str, str] = {"Merqury": "\u2020", "MerquryFK": "\u2021"}  # † ‡

def _format_marked_column(df: pd.DataFrame, column: str, tool_column: str,
    marker_map: dict[str, str], legend: dict[str, str], legend_text_fn) -> pd.Series:
    """
    Attaches a tool marker to every (non-missing) cell value in a column, based on the tool used in that ROW.
    Intended for DISPLAY purposes only (string result); the original numeric column in super_table remains unchanged.
    """
    def _fmt(row):
        value = row[column]
        if pd.isna(value):
            return ""
        tool = row.get(tool_column)
        marker = marker_map.get(tool, "")
        if marker:
            legend[marker] = legend_text_fn(tool)
        return f"{value:.2f}{marker}"
    return df.apply(_fmt, axis=1)

def _format_haploid_number(row: pd.Series) -> str:
    """
    Indicates the haploid number with a warning marker if GoaT-Source isn't 'direct'.
    """
    value = row.get("haploid_number")
    if value is None or pd.isna(value):
        return ""
    source = row.get("haploid_source")
    marker = "" if source == "direct" else "\u26A0"  # ⚠ 
    return f"{int(value)}{marker}"

def _prepare_display_table(
    super_table: pd.DataFrame,
    human_readable_bp: bool = False
    ) -> tuple[pd.DataFrame, dict[str, str]]:
    """
    General preparing-logic for render_markdown_table() and rende_html_heatmap().
    - haploid-number-marker, bp-scaling, sci-notation, tool-marker for gene-completess and k-mer-analysis, lineage legend, renaming of columns
    
    - rating-columns are not removed yet:
        - render_markdown_table() shows them as text-columns
        - render_html_heatmap() uses them for color coding and removes them afterwards
        
    Returns tuple(prepared table, legend)
    """
    df = super_table.copy()
    legend: dict[str, str] = {}
    
    # Bring ordered Columns to the front of the table
    ordered_known = [c for c in COLUMN_ORDER if c in df.columns]
    remaining = [c for c in df.columns if c not in ordered_known]
    df = df[ordered_known + remaining]
    
    
    if "haploid_number" in df.columns:
        has_non_direct = (
            "haploid_source" in df.columns
            and df["haploid_source"].fillna("direct").ne("direct").any()
        )
        df["haploid_number"] = df.apply(_format_haploid_number, axis=1)
        if has_non_direct:
            legend["\u26A0"] = {
                "text_before": "Haploid number is an estimation by",
                "link_text": "GoaT",
                "link": "https://goat.genomehubs.org"
            }
            
    # bp-scaled columns: fix scientific notation (e.g. "1e+03") + optional Kb/Mb/Gb display
    for col in BP_SCALE_COLUMNS:
        if col in df.columns:
            df[col] = df[col].apply(lambda v: _format_bp(v, human_readable_bp))
 
    # other numeric columns: scientific-notation fix only, no units
    for col, decimals in PLAIN_NUMERIC_COLUMNS.items():
        if col in df.columns:
            df[col] = df[col].apply(lambda v, d=decimals: _format_plain_numeric(v, d))
 
    for col in COMPLETENESS_COLUMNS:
        if col in df.columns:
            df[col] = _format_marked_column(
                df, col, "completeness_tool", COMPLETENESS_TOOL_MARKERS, legend,
                lambda tool: f"Gene-Completeness done with {tool}"
            )
 
    for col in KMER_COLUMNS:
        if col in df.columns:
            df[col] = _format_marked_column(
                df, col, "kmer_tool", KMER_TOOL_MARKERS, legend,
                lambda tool: f"k-mer-Analysis done with {tool}"
            )
    
    df["lineage"] = df["lineage"].fillna("") if "lineage" in df.columns else ""
    
    for col in list(df.columns):
        if col in PROTECTED_COLUMNS:
            continue
        is_all_empty = df[col].apply(
            lambda v: v is None
            or (isinstance(v, float) and pd.isna(v))
            or (isinstance(v, str) and v.strip() == "")
        ).all()
        if is_all_empty:
            df = df.drop(columns=[col])

    df = df.drop(columns=["completeness_tool", "kmer_tool", "haploid_source"], errors="ignore")
    df = df.rename(columns=COLUMN_DISPLAY_NAMES)
 
    return df, legend 


def render_markdown_table(
    super_table: pd.DataFrame,
    human_readable_bp: bool = False,
) -> str:
    """
    Markdown table with tool-neutral column names and footnote markers
    per row (e.g., "86.82*"), instead of tool-specific column names or
    a generic header row (which could be incorrect in mixed reports).
    """

    df, legend = _prepare_display_table(super_table, human_readable_bp)

    lines = [
        "# GEP2 Super-Report",
        "",
        f"- **Assemblies in this report:** {super_table['asm_id'].nunique()}",
        ""
    ]

    lines.append(df.to_markdown(index=False))
    lines.append("")
    
    if legend:
        for marker, text in sorted(legend.items()):
            if isinstance(text, dict):
                text = f"{text['text_before']} [{text['link_text']}]({text['link']})"
            lines.append(f"'{marker}'   {text}  ")
        lines.append("")
        
    return "\n".join(lines)


RATING_COLORS: dict[str, str] = {
    "****": "#0072b2bf",  # Way above threshold
    "***-": "#009e73bf",  # At or above threshold
    "**--": "#e69f00bf",  # Below threshold
    "*---": "#cc79a7bf",  # Way below threshold
    "····": "#f0f0f0bf",  # no rating -> neutral
}

VALUE_DISPLAY_TO_RATING_COLUMN: dict[str, str] = {
    "Contig N50": "contig_n50_rating",
    "Scaffold N50": "scaffold_n50_rating",
    "Gaps/Gbp": "gaps_per_gbp_rating",
    "Scaffold L90": "scaffold_l90_rating",
    "Gene Compl. Single (%)": "gene_compl_single_rating",
    "Gene Compl. Dupl. (%)": "gene_compl_dupl_rating",
    "k-mer QV": "merqury_qv_rating",
    "k-mer Compl. (%)": "merqury_completeness_rating",
}


def render_html_heatmap(
    super_table: pd.DataFrame,
    human_readable_bp: bool = False,
    source_reports: Optional[list[str]] = None,
) -> str:
    """Render the SuperTable as a color-coded HTML heatmap.

    Rating columns are used to color the corresponding value columns.
    
    Metadata, legends, and origin information are included below the report title and table.
    """
    df, legend = _prepare_display_table(super_table, human_readable_bp)


    style_df = pd.DataFrame("", index=df.index, columns=df.columns)

    for value_column, rating_column in VALUE_DISPLAY_TO_RATING_COLUMN.items():
        if value_column not in df.columns or rating_column not in df.columns:
            continue

        style_df[value_column] = df[rating_column].map(
            lambda rating: (
                f"background-color: {RATING_COLORS.get(rating, '')}"
            )
        )

    # remove rating columns
    rating_columns = [column for column in df.columns if column.endswith("_rating")]
    df = df.drop(columns=rating_columns)
    style_df = style_df.drop(columns=rating_columns)

    # Let pandas handle the table HTML generation.
    styler = (
        df.style
        .apply(lambda _: style_df, axis=None)
        .hide(axis="index")
    )

    text_columns = [column for column in TEXT_COLUMNS if column in df.columns]
    if text_columns:
        styler = styler.set_properties(
            subset=text_columns,
            **{"text-align": "left"},
        )

    table_html = styler.to_html()

    # ------------------------------------------------------------------
    # Report metadata
    # ------------------------------------------------------------------
    n_species = (
        int(super_table["species"].nunique())
        if "species" in super_table.columns
        else 0
    )

    n_assemblies = (
        int(
            super_table[["species", "asm_id"]]
            .drop_duplicates()
            .shape[0]
        )
        if {"species", "asm_id"}.issubset(super_table.columns)
        else 0
    )

    n_files = len(super_table)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    metadata = {
        "Generated": generated_at,
        "Species": str(n_species),
        "Assemblies": str(n_assemblies),
        "Files": str(n_files),
    }

    meta_html = "".join(
        f"""
        <div class="meta-item">
            <span class="meta-label">{label}</span>
            <span class="meta-value">{value}</span>
        </div>
        """
        for label, value in metadata.items()
    )

    # ------------------------------------------------------------------
    # Rating legend
    # ------------------------------------------------------------------
    rating_legend = (
        ("****", " Exceeds threshold"),
        ("***-", " Meets threshold"),
        ("**--", " Below threshold"),
        ("*---", " Far below threshold"),
        ("····", " No rating available"),
    )

    rating_legend_html = "".join(
        f"""
        <li>
            <span
                class="swatch"
                style="background-color: {RATING_COLORS[rating]}"
            ></span>
            {label} <code> ({rating}) </code>
        </li>
        """
        for rating, label in rating_legend
    )

    # ------------------------------------------------------------------
    # Marker / footnote legend
    # ------------------------------------------------------------------
    marker_legend_html = ""

    if legend:
        marker_legend_html = "".join(
            f"""
            <li>
                <code>{marker}</code>
                <span>{text}</span>
            </li>
            """
            for marker, text in sorted(legend.items())
        )

    # Process legend entries, converting dicts to HTML links
    processed_legend = {}
    for marker, text in legend.items():
        if isinstance(text, dict):
            text = f'{text["text_before"]} <a href="{text["link"]}" target="_blank">{text["link_text"]}</a>'
        processed_legend[marker] = text
    
    marker_legend_html = ""
    if processed_legend:
        marker_legend_html = "".join(
            f"""
            <li>
                <code>{marker}</code>
                <span>{text}</span>
            </li>
            """
            for marker, text in sorted(processed_legend.items())
        )
    
    marker_legend_box = ""
    if marker_legend_html:
        marker_legend_box = f"""
        <div class="legend-box">
            <h3>Markers &amp; Footnotes</h3>
            <ul class="legend">
                {marker_legend_html}
            </ul>
        </div>
        """

    legend_html = f"""
    <div class="legend-container">
        <div class="legend-box">
            <h3>Rating Colors</h3>
            <p style="font-size: 0.85em; color: #666; margin-bottom: 0.8em;">
                Thresholds are related to <a href="https://www.earthbiogenome.org/report-on-assembly-standards" target="_blank">EBP Assembly Standards</a>.
            </p>
            <ul class="rating-legend">
                {rating_legend_html}
            </ul>
        </div>
        {marker_legend_box}
    </div>
    """

    # ------------------------------------------------------------------
    # Origin footer
    # ------------------------------------------------------------------
    footer = f"<footer>Generated by GEP2 Super-Report v{__version__}"

    if source_reports:
        report_names = ", ".join(
            os.path.basename(path) for path in source_reports
        )
        footer += (
            f" &middot; Aggregated from {len(source_reports)} "
            f"report file(s): {report_names}"
        )

    footer += "</footer>"

    # ------------------------------------------------------------------
    # Final HTML document
    # ------------------------------------------------------------------
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>GEP2 Super-Report</title>
<style>
:root {{
    --accent: #2c3e50;
}}

body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                 Helvetica, Arial, sans-serif;
    margin: 2em auto;
    max-width: 1500px;
    padding: 0 1.5em;
    color: #222;
    line-height: 1.45;
}}

h1 {{
    margin-bottom: 0.15em;
    font-size: 1.9em;
    border-bottom: 3px solid var(--accent);
    padding-bottom: 0.35em;
}}

.subtitle {{
    color: #666;
    margin-top: 0.2em;
    margin-bottom: 1.3em;
    font-size: 0.95em;
}}

.report-meta {{
    display: flex;
    flex-wrap: wrap;
    background: #f4f6f8;
    border: 1px solid #e0e0e0;
    border-radius: 6px;
    padding: 0.7em 0;
    margin-bottom: 1.6em;
}}

.meta-item {{
    padding: 0 1.6em;
    border-right: 1px solid #d8d8d8;
}}

.meta-item:last-child {{
    border-right: none;
}}

.meta-label {{
    display: block;
    font-size: 0.72em;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #888;
}}

.meta-value {{
    display: block;
    font-size: 1.15em;
    font-weight: 600;
    color: var(--accent);
}}

.table-wrap {{
    overflow-x: auto;
    border: 1px solid #ddd;
    border-radius: 6px;
}}

table {{
    border-collapse: collapse;
    width: 100%;
    font-size: 0.9em;
}}

th,
td {{
    border: 1px solid #e6e6e6;
    padding: 7px 11px;
    text-align: right;
    white-space: nowrap;
}}

th {{
    background-color: var(--accent);
    color: white;
    position: sticky;
    top: 0;
    font-weight: 600;
    text-align: left;
}}

tbody tr:nth-child(even) td {{
    background-color: #f7f8fa;
}}

tr:hover td {{
    filter: brightness(0.95);
}}

.legend-container {{
    display: flex;
    gap: 1.4em;
    flex-wrap: wrap;
    margin-top: 1.8em;
}}

.legend-box {{
    background: #fafafa;
    border: 1px solid #e0e0e0;
    border-radius: 6px;
    padding: 1em 1.4em;
    flex: 1;
    min-width: 280px;
}}

.legend-box h3 {{
    margin: 0 0 0.7em 0;
    font-size: 0.9em;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #555;
    border-bottom: 1px solid #ddd;
    padding-bottom: 0.45em;
}}

ul.rating-legend,
ul.legend {{
    list-style: none;
    padding-left: 0;
    margin: 0;
}}

ul.rating-legend li,
ul.legend li {{
    display: flex;
    align-items: center;
    margin-bottom: 0.55em;
    font-size: 0.88em;
}}

ul.legend code {{
    background: #eaeaea;
    padding: 4px 9px;
    border-radius: 4px;
    font-size: 1.05em;
    margin-right: 0.8em;
    min-width: 1.3em;
    text-align: center;
    display: inline-block;
}}

ul.rating-legend code {{
    font-weight: bold;
    font-size: 1.15em;
    letter-spacing: 0.05em;
}}

.swatch {{
    display: inline-block;
    width: 14px;
    height: 14px;
    border: 1px solid #999;
    border-radius: 2px;
    margin-right: 0.7em;
    flex-shrink: 0;
}}

footer {{
    margin-top: 2.2em;
    padding-top: 1em;
    border-top: 1px solid #e6e6e6;
    font-size: 0.78em;
    color: #999;
}}

@media print {{
    th {{
        background-color: #eee !important;
        color: #000 !important;
        position: static;
    }}

    .table-wrap {{
        overflow-x: visible;
    }}
}}
</style>
</head>

<body>
<h1>GEP2 Super-Report</h1>

<p class="subtitle">
    Aggregated genome assembly quality overview across multiple
    GEP2 reports
</p>

<div class="report-meta">
    {meta_html}
</div>

<div class="table-wrap">
    {table_html}
</div>

{legend_html}

{footer}
</body>
</html>
"""


# -------------------------------------------------------------------------------
# CLI ENTRY POINT
# -------------------------------------------------------------------------------

def main() -> None:
    # ---------------------------------------------------------------
    # ------------------------ CLI-Section: -------------------------
    parser = argparse.ArgumentParser(
        description="Creates a 'super-report' across multiple {asm_id}_report.md-files created by the 'make_gep2_report.py'-script."
    )
    parser.add_argument(
        "--reports", required=True, nargs="+",
        help="paths to {asm_id}_report.md files"
    )
    parser.add_argument(
        "--output", required=True,
        help="output name of the super-report."
    )
    parser.add_argument(
        "--format", choices=["markdown", "html"], default="markdown",
        help="format of output file."
    )
    parser.add_argument(
        "--human-readable", action="store_true",
        help="shows bp-values as Kb/Mb/Gb instead of raw values."
    )
    
    args: argparse.Namespace = parser.parse_args()
    
    missing = [p for p in args.reports if not os.path.exists(p)]
    if missing:
        print(f"Error: report file(s) not found: {missing}", file=sys.stderr)
        sys.exit(1)
    # ---------------------------------------------------------------
    # ------------------ Aggregating of Results: --------------------

    all_data: list[dict[str, Any]] = [parse_assembly_report(p) for p in args.reports]
 
    print("\nImported Reports:")
    for data in all_data:
        print(f"  {data['species']} / {data['asm_id']} (Completeness: {data['completeness_tool']}, k-mer: {data['kmer_tool']})")   
        print(f"{data['metrics']}")
    super_table: pd.DataFrame = build_super_table(all_data)

    # ---------------------------------------------------------------
    # ------------------------- Output: -----------------------------
 
    output_text: str
    if args.format == "markdown":
        output_text = render_markdown_table(super_table, human_readable_bp=args.human_readable)
    else:
        output_text = render_html_heatmap(
            super_table, human_readable_bp=args.human_readable, source_reports=args.reports
        )
 
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(output_text)
 
    print(f"\n'super-report' written to: {args.output}")


if __name__ == "__main__":
    main()
